import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./context/AuthContext";
import { Toaster } from "sonner";
import { Figtree } from 'next/font/google';
import Navbar from "./components/Navbar";

const figtree = Figtree({
  subsets: ['latin'],
  variable: '--font-figtree', // Creates the CSS variable mapping hook
  display: 'swap',
})



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${figtree.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        
        <AuthProvider>
          <Navbar/>
          {children}</AuthProvider>
        <Toaster richColors closeButton position="top-center" />
        </body>
    </html>
  );
}
